name: Build and Deploy CV to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install .

      - name: Install Playwright browser for PDF generation
        run: |
          pip install playwright
          playwright install chromium

      - name: Run main.py to generate HTML and PDF
        run: python -m cvgen.main

      - name: Create release tag with timestamp
        id: tag
        run: echo "tag=cv-$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: CV Release ${{ steps.tag.outputs.tag }}
          body: |
            Automated CV release generated on $(date +'%Y-%m-%d at %H:%M UTC')
            
            This release contains the latest PDF version of the CV.
          files: ./html/owen-williams-*.pdf
          draft: false
          prerelease: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
